### PR TITLE
Pooch integration, mark online tests, better handle online-dependent documentation, distributed testing

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
  - This PR addresses issues raised in #183 
- [x] (If applicable) Documentation has been added / updated (for bug fixes / features).
- [x] (If applicable) Tests have been added.
- [x] CHANGELOG.rst has been updated (with summary of main changes).
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.

### What kind of change does this PR introduce?

* Marks several tests reliant on external services (`online`).
* Better typing in call signatures.
* Removes several unused imports.
* Added `pytest-xdist` to the development dependencies.
* Adding in a `pooch` registry for verifying file integrity when fetching testing data.

### Does this PR introduce a breaking change?

Yes. `pytest-xdist` is now a development dependency. By default, it is not being used, but it can be enabled by providing positional arguments to the `pytest` call.

### Other information:

I've copied and slightly improved upon the new testing data system currently in #175. I'll handle the merge of the changes to there, but this current system is nearing finalization. The last thing that I'm waiting on are some changes from @RondeauG to `xhydro-testdata` so that I can make a dated tag that will become the default testing data branch for `xhydro` (updated whenever there are additions to `xhydro-testdata`). This will help prevent breakages from a moving `main` branch over there.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
I need to convert the exiting pooch calls to the new system, but before that, the pooch-based setup code causing errors at the moment needs to be converted to pytest fixtures. Will tackle that tomorrow.

**Comment by sebastienlanglois** [comment]
@Zeitsperre I have implemented the fix for the GIS module here : https://github.com/hydrologie/xhydro/pull/213

**Review by sebastienlanglois — APPROVED** [review]
Impressive work, thanks for improving the quality of the codebase!

**Review by RondeauG — APPROVED** [review]
We'll see if the GIS notebook passes. Otherwise, we might need to run the outputs locally as was done before.

(Note that I didn't include that notebook in #211, since it wasn't run by RtD).

**Pull request merged**
